import {createHash,createHmac,randomBytes,timingSafeEqual} from 'node:crypto';
export function hash(token){return createHash('sha256').update(token).digest('hex')}
// Non-identifying, coarse browser-device match hint. Never use as an authentication factor.
export function deviceAliasHash(proof,secret){return /^[a-f0-9]{64}$/.test(String(proof||''))?createHmac('sha256',secret).update('mio-device-match-v1:'+proof).digest('hex'):''}
function config(){const url=process.env.APPS_SCRIPT_URL||'https://script.google.com/macros/s/AKfycbyR2ujPRmZFBzdx8NGjIH4HmwHQYlpAgsLgZE5qJS-XkHuz6yZn1rfj2L27g6oKTyMIYA/exec';const secret=process.env.APPS_SCRIPT_SECRET;if(!secret||secret.length<32)throw Error('本番連携キーが未設定です');const u=new URL(url);if(u.protocol!=='https:'||u.hostname!=='script.google.com'||!/^\/macros\/s\/[^/]+\/exec$/.test(u.pathname))throw Error('連携URLが不正です');return {url,secret}}
export function sessionCookie(id,token,secret){const encoded=Buffer.from(JSON.stringify({id,token})).toString('base64url');const signature=createHmac('sha256',secret).update(encoded).digest('base64url');return 'mio_session='+encoded+'.'+signature+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=7776000'}
export function readSession(cookie,secret){try{const v=(cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('mio_session='))?.slice(12);if(!v)return null;const [data,sig,...extra]=v.split('.');if(extra.length)return null;const expected=createHmac('sha256',secret).update(data).digest();const provided=Buffer.from(sig,'base64url');if(expected.length!==provided.length||!timingSafeEqual(expected,provided))return null;const s=JSON.parse(Buffer.from(data,'base64url'));return /^MIO-W-[a-f0-9]{24}$/.test(s.id)&&/^[a-f0-9]{64}$/.test(s.token)?s:null}catch{return null}}
export function makeIdentity(){return {id:'MIO-W-'+randomBytes(12).toString('hex'),token:randomBytes(32).toString('hex')}}
export async function bridge(action,payload){const {url,secret}=config();const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,secret,...payload}),redirect:'follow',signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('連携先に接続できません');const d=await r.json();if(!d.ok)throw Error(d.error||'連携処理に失敗しました');return d}
export function prepare(req,res){res.setHeader('Cache-Control','private, no-store');res.setHeader('X-Content-Type-Options','nosniff');if(req.method!=='POST'){res.setHeader('Allow','POST');res.status(405).json({ok:false,error:'POSTを使用してください'});return null}const origin=req.headers.origin;if(origin){try{if(new URL(origin).host!==req.headers.host)throw Error()}catch{res.status(403).json({ok:false,error:'別サイトからの操作はできません'});return null}}try{return config()}catch(e){res.status(503).json({ok:false,error:e.message});return null}}
