const $=id=>document.getElementById(id);
let participant='',busy=false,lastCatalog=null;
const key=()=>`mio_pending_draw_${participant||'unknown'}`;
function note(t){const el=$('drawMessage');if(el)el.textContent=t||''}
function remember(){try{return JSON.parse(localStorage.getItem(key())||'null')}catch{return null}}
function forget(){try{localStorage.removeItem(key())}catch{}}
function parse(text){try{return text?JSON.parse(text):{}}catch{return {ok:false,error:'応答を確認できませんでした'}}}
function xhrPost(body){return new Promise((resolve,reject)=>{const x=new XMLHttpRequest();x.open('POST','/api/gacha',true);x.setRequestHeader('Content-Type','application/json');x.setRequestHeader('Accept','application/json');x.timeout=20000;x.withCredentials=true;x.onload=()=>{const d=parse(x.responseText);if(x.status>=200&&x.status<300){resolve(d);return}const e=Error(d.error||`接続できませんでした (${x.status})`);e.status=x.status;reject(e)};x.onerror=()=>reject(Error('通信に失敗しました'));x.ontimeout=()=>reject(Error('通信がタイムアウトしました'));x.send(JSON.stringify(body))})}
async function post(body){try{const r=await fetch('/api/gacha',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},credentials:'same-origin',body:JSON.stringify(body),cache:'no-store'});const d=parse(await r.text());if(!r.ok){const e=Error(d.error||'結果の確認に失敗しました');e.status=r.status;throw e}return d}catch(e){if(e&&typeof e.status==='number')throw e;return xhrPost(body)}}
function safeImage(url){return typeof url==='string'&&/^https:\/\//i.test(url)?url:''}
function card(target,c){target.replaceChildren();const text=document.createElement('p');text.className='catalog-status';text.textContent=c.message;target.append(text);for(const p of c.prizes||[]){const row=document.createElement('div');row.className='prize';const image=safeImage(p.image);if(image){const img=document.createElement('img');img.src=image;img.alt='';img.loading='lazy';img.referrerPolicy='no-referrer';img.addEventListener('error',()=>img.remove(),{once:true});row.append(img)}const meta=document.createElement('div');const name=document.createElement('strong');name.textContent=p.name;meta.append(name);const sub=document.createElement('span');sub.textContent=`${p.rarity?p.rarity+' · ':''}${p.chance}%`;meta.append(sub);row.append(meta);target.append(row)}}
function showResult(d){const stage=$('gachaStage'),card=$('drawResultCard'),img=$('drawResultImage');stage.classList.toggle('is-fest',d.mode==='ラキフェス');card.hidden=false;$('drawRarity').textContent=d.rarity||'';$('drawPrizeName').textContent=d.prize||'当選';$('drawOrdinal').textContent=`${d.ordinal}回目${d.replayed?'（確認済み結果）':''}`;const image=safeImage(d.image);if(image){img.src=image;img.alt=d.prize||'当選景品';img.hidden=false;img.onerror=()=>{img.hidden=true}}else{img.hidden=true;img.removeAttribute('src')}}
function clearResult(){const card=$('drawResultCard');if(card)card.hidden=true;const stage=$('gachaStage');if(stage)stage.classList.remove('is-fest')}
function setButtons(c){const pending=remember();$('drawNormal').disabled=!!pending||!c.confirmed||c.remaining<1||!c.normal.ready;$('drawFest').disabled=!!pending||!c.confirmed||c.remaining<1||!c.festUnlocked||!c.fest.ready;$('retryDraw').hidden=!pending}
function statusText(c){if(!c.confirmed)return 'メンシプ購入の確認をお待ちください。';if(c.remaining<1)return 'ガチャ権利をすべて使用済みです。';if(!c.normal.ready&&!c.fest.ready)return '景品設定中です。運営の設定完了後に抽選できます。';if(!c.festUnlocked)return '通常ガチャを利用できます。総ガチャ権利5回以上でラキフェスが解放されます。';return '通常／ラキフェスを選んで抽選できます。'}
async function reload(){if(busy)return;busy=true;try{const c=await post({action:'catalog'});lastCatalog=c;participant=c.participantId;$('drawPanel').hidden=false;$('drawRemaining').textContent=`ガチャ残り ${c.remaining}回 ／ 使用済み ${c.used}回`;card($('normalPrizes'),c.normal);card($('festPrizes'),c.fest);setButtons(c);const pending=remember();note(pending?'前回の抽選結果が未確認です。「前回の結果を確認」を押してください。':statusText(c));const h=await post({action:'history'});$('drawHistory').replaceChildren();if(!h.history?.length){const li=document.createElement('li');li.className='muted';li.textContent='まだ当選履歴はありません。';$('drawHistory').append(li)}else for(const x of h.history){const li=document.createElement('li');li.className=`history-item ${x.mode==='ラキフェス'?'fest-history':''}`;const image=safeImage(x.image);if(image){const img=document.createElement('img');img.src=image;img.alt='';img.loading='lazy';img.addEventListener('error',()=>img.remove(),{once:true});li.append(img)}const text=document.createElement('span');text.innerHTML='';const title=document.createElement('strong');title.textContent=x.prize;const sub=document.createElement('small');sub.textContent=`${x.ordinal}回目 · ${x.mode}${x.rarity?' · '+x.rarity:''}`;text.append(title,sub);li.append(text);$('drawHistory').append(li)}}catch(e){$('drawPanel').hidden=false;$('drawNormal').disabled=true;$('drawFest').disabled=true;note(e.message)}finally{busy=false}}
async function execute(pending){if(busy)return;busy=true;$('drawNormal').disabled=true;$('drawFest').disabled=true;$('retryDraw').disabled=true;clearResult();$('crystal').classList.add('spinning');$('gachaStage').classList.toggle('is-fest',pending.mode==='ラキフェス');note(pending.mode==='ラキフェス'?'ステージ開演…抽選しています':'抽選しています…');try{const d=await post({action:'draw',...pending});showResult(d);forget();note(`${d.ordinal}回目の結果を保存しました。残り ${Math.max(0,Number(d.remaining??0))}回。`)}catch(e){note(`${e.message}。「前回の結果を確認」から同じ抽選を確認できます。`);$('retryDraw').hidden=false}finally{$('crystal').classList.remove('spinning');busy=false;$('retryDraw').disabled=false;await reload();document.getElementById('refresh')?.click()}}
function makeId(){return crypto.randomUUID?crypto.randomUUID().replaceAll('-',''):Array.from(crypto.getRandomValues(new Uint8Array(16)),x=>x.toString(16).padStart(2,'0')).join('')}
function start(mode){if(!participant||busy||remember())return;if(!lastCatalog)return;const available=mode==='通常'?lastCatalog.normal.ready:lastCatalog.festUnlocked&&lastCatalog.fest.ready;if(!available)return;if(!window.confirm(`${mode}ガチャを1回引きます。共通のガチャ権利を1回消費します。よろしいですか？`))return;const p={drawId:makeId(),mode};try{localStorage.setItem(key(),JSON.stringify(p))}catch{note('端末に抽選確認情報を保存できないため、抽選は開始しません。');return}execute(p)}
$('drawNormal')?.addEventListener('click',()=>start('通常'));
$('drawFest')?.addEventListener('click',()=>start('ラキフェス'));
$('retryDraw')?.addEventListener('click',()=>{const p=remember();if(p)execute(p)});
$('reloadGacha')?.addEventListener('click',reload);
export async function updateGacha(id,approved){participant=id;if(!approved){$('drawPanel').hidden=true;return}await reload()}
