const $=id=>document.getElementById(id);
let participant='',busy=false;
const key=()=>`mio_pending_draw_${participant}`;
function note(t){$('drawMessage').textContent=t}
function remember(){try{return JSON.parse(localStorage.getItem(key())||'null')}catch{return null}}
async function post(b){const r=await fetch('/api/gacha',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(b),cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'結果の確認に失敗しました');return d}
function card(target,c){target.replaceChildren();const text=document.createElement('p');text.textContent=c.message;target.append(text);for(const p of c.prizes){const row=document.createElement('div');row.className='prize';if(p.image&&/^https:\/\//i.test(p.image)){const img=document.createElement('img');img.src=p.image;img.alt=p.name;img.loading='lazy';img.referrerPolicy='no-referrer';img.style.cssText='width:64px;height:64px;object-fit:cover;border-radius:12px;display:block;margin:0 0 6px';img.addEventListener('error',()=>img.remove(),{once:true});row.append(img)}const label=document.createElement('span');label.textContent=`${p.rarity?p.rarity+' · ':''}${p.name}　${p.chance}％`;row.append(label);target.append(row)}}
async function reload(){if(busy)return;busy=true;try{const c=await post({action:'catalog'});participant=c.participantId;$('drawPanel').hidden=false;card($('normalPrizes'),c.normal);card($('festPrizes'),c.fest);$('drawRemaining').textContent=`残り ${c.remaining}回 ／ 次は通算 ${c.used+1}回目`;const pending=remember();$('drawNormal').disabled=!!pending||!c.confirmed||c.remaining<1||!c.normal.ready;$('drawFest').disabled=!!pending||!c.confirmed||c.remaining<1||!c.festUnlocked||!c.fest.ready;$('retryDraw').hidden=!pending;note(pending?'前回の抽選結果が未確認です。「前回の結果を確認」を押してください。':!c.confirmed?'メンシプ購入の確認をお待ちください。':!c.festUnlocked?'総ガチャ権利5回以上でラキフェスが解放されます。':'通常／ラキフェスを選べます。');const h=await post({action:'history'});$('drawHistory').replaceChildren();for(const x of h.history){const li=document.createElement('li');li.textContent=`${x.ordinal}回目 · ${x.mode} · ${x.prize}`;$('drawHistory').append(li)}}catch(e){$('drawPanel').hidden=false;$('drawNormal').disabled=true;$('drawFest').disabled=true;note(e.message)}finally{busy=false}}
async function execute(pending){if(busy)return;busy=true;$('drawNormal').disabled=true;$('drawFest').disabled=true;$('retryDraw').disabled=true;$('drawResult').textContent='';$('crystal').classList.add('spinning');note('抽選結果を確認しています…');try{const d=await post({action:'draw',...pending});$('drawResult').textContent=`${d.prize} 🎉`;$('drawResult').setAttribute('data-mode',d.mode);localStorage.removeItem(key());note(`${d.ordinal}回目の結果を保存しました。`)}catch(e){note(`${e.message}。「前回の結果を確認」から同じ抽選を確認できます。`);$('retryDraw').hidden=false}finally{$('crystal').classList.remove('spinning');busy=false;$('retryDraw').disabled=false;await reload();document.getElementById('refresh').click()}}
function start(mode){if(!participant||busy||remember())return;if(!window.confirm(`${mode}ガチャを1回引きます。残り回数を1回消費します。よろしいですか？`))return;const id=(crypto.randomUUID?crypto.randomUUID().replaceAll('-',''):Array.from(crypto.getRandomValues(new Uint8Array(16)),x=>x.toString(16).padStart(2,'0')).join(''));const p={drawId:id,mode};try{localStorage.setItem(key(),JSON.stringify(p))}catch{note('端末に抽選確認情報を保存できません。抽選は開始しません。');return}execute(p)}
$('drawNormal').addEventListener('click',()=>start('通常'));$('drawFest').addEventListener('click',()=>start('ラキフェス'));$('retryDraw').addEventListener('click',()=>{const p=remember();if(p)execute(p)});$('reloadGacha').addEventListener('click',reload);
export async function updateGacha(id,approved){participant=id;if(!approved){$('drawPanel').hidden=true;return}await reload()}
